# This file is an override; do not run alone.
# Use together with docker-compose.yml:
#   docker compose -f docker-compose.yml -f docker-compose.local.yml up --build
version: "3.8"

x-affine-image: &affine_image
  image: affine:local
  build:
    context: .
    dockerfile: Dockerfile

services:
  validator:
    <<: *affine_image
  runner:
    <<: *affine_image
  signer:
    <<: *affine_image 
