[project]
name = "affine"
version = "0.1.0"
description = "Anima Machina"
authors = [{ name = "affine", email = "affine@affine.io" }]
dependencies = [
    "python-dotenv>=0.21.0",
    "bittensor",
    "bittensor-cli",
    "chutes",
    "aiohttp>=3.10.11",
    "ipykernel>=6.30.1",
    "click>=8.0.0",
    "click-log>=0.4.0",
    "alive_progress>=3.0.0",
    "pydantic>=2.6",
    "numpy>=1.24",
    "redis==5.*",
    "boto3>=1.34",
    "huggingface_hub",
    "datasets",
    "aiobotocore>=2.23.0",
    "botocore>=1.38.27",
    "tabulate>=0.9.0",
    "prometheus-client>=0.21.0",
    "scipy>=1.11.0",
    # Dependencies from Quixand
    "anyio>=4.0",
    "orjson>=3.10",
    "websockets>=12.0",
    "ptyprocess>=0.7",
    "typer>=0.12",
    "rich>=13.7",
    "build>=1.3.0",
    "twine>=6.1.0",
    "docker>=7.0",
    "podman>=4.0",
    "fastapi>=0.110.1",
]
readme = "README.md"
requires-python = ">=3.11"

[project.scripts]
af = "affine:cli"
qs = "affine.quixand.cli.main:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["affine"]

[tool.uv.sources]
affine = { path = ".", editable = true }
